### ISSUE TITLE
I hate to put offtopic stuff here, but you're being pretty hostile

### ISSUE THREAD

**Issue by NancokPS2** [GirafiStudios/MineMenu#103]
I saw that you where against fabric and about your mods getting support at ALL (i don't use it myself mind you) because some of the community was "childish" which is a pretty terrible reason to say the least (it's literally just a method of modding, what your notion of their userbase may be doesn't have anything to do with supporting it or not)
Then a guy asked for a discord and instead of a yes or no you just closed his request twice and marked it as spam
There's also the fact that you blocked comments in the curseforge page
I'm not trying to attack you, but think it over, not everyone is the bad guy

**Comment by GirafiStudios** [comment]
Somebody is porting Mine Menu to Fabric atm. 
He could find the Discord information, if he looked at some of my other mods CF page. 

I'm not sure where you have the idea of not supporting my mods from, I spend hundreds of hours a year doing so. It's just Mine Menu, that I don't really care about much, but still do some updating. 
Comments on CF is off for some of my mods, because people kept asking the exact same questions hundreds of times. 

As for Fabric, I do not intend to ever have anything to do with it, after getting death treats for not updating the mod I at the time did support for Fabric.
