### ISSUE TITLE
MineMenu Triggering Unwanted Actions

### ISSUE THREAD

**Issue by SwissxCore** [GirafiStudios/MineMenu#113]
Minecraft Version: 1.16.5
Forge Version: 36.1.0
Mod Version: 1.16.4-1.8.7

When setting up and selecting an option from the radial menu, multiple other buttons are being pressed at the same time, specifically, my W key is toggled so I start moving forwards without pressing anything, and the GUI for the mod "Chunk Pregenerator" opens; the action I had set does not trigger despite hitting the other actions.

It should be noted that although Chunk Pregenerator has the option for a key to be bound, I've elected to keep it unbound, so this mod is triggering the action even without a key.

**Comment by TristanKing0** [comment]
I'm facing the same issue. This is unusable. I try to select anything and it toggles me walking forward, sitting down, does some stupid emote, etc.

**Comment by TristanKing0** [comment]
I've worked it out! It's just because you're selecting a control that has a blank keybind, and the way this mod works is it just triggers that keybind, meaning it will trigger all other blank keybind controls too.

I think the mod needs to be more clear that what control you select will trigger all other controls that are set to the same keybind, and have a warning for blank keybinds.

**Comment by Seikikai** [comment]
This Also Happens To Me And Isn't Due That In My Case

**Comment by DoomRater** [comment]
I should note that I am not experiencing this on 1.12.2-1.6.11.

**Comment by Warhand** [comment]
Still occurs in the latest, and frankly ruins a lot of potential usecases for this mod when it comes to freeing up keybinds by putting them in this menu, since the controls still need to be assigned a unique key.

Imo it would be a major QOL change if assigning a control to a menu option in minemenu assigned that control to a dummy keybind, that can only be activated by minemenu.

**Comment by KazuMurako** [comment]
> Still occurs in the latest, and frankly ruins a lot of potential usecases for this mod when it comes to freeing up keybinds by putting them in this menu, since the controls still need to be assigned a unique key.
> 
> Imo it would be a major QOL change if assigning a control to a menu option in minemenu assigned that control to a dummy keybind, that can only be activated by minemenu.

I'm having the same issue in 1.18.2 Forge 40.1.68 MineMenu 1.10.0
All unbound keys get activated at the same time ruining any chance I had at using this mod.
I bind something like a Quark Emote to the radial menu, and when I press it, the emote plays but it also opens the curios menu. Both keys are unbound in the regular Minecraft keybinds menu.

**Comment by GirafiStudios** [comment]
Should be fixed in the Minecraft 1.19.4 version of MineMenu :)

**Comment by loldev69** [comment]
If you can't backport this to the other versions, can you please add a warning to those versions to let users know of the problem?
