### ISSUE TITLE
MOD Crash on reload [version 1.20.4 fabric0.15.6]

### ISSUE THREAD

**Issue by Momeyuka** [GirafiStudios/MineMenu#167]
Hello, mod developers. 

Please help me. Thank you.

After installing your mod I started the game for the first time and it ran fine, but when I closed the game and restarted it, the game crashed before it even started, I love this portable mod, but the crashes are killing me!

I'm using version 0.15.6 with the 1.20.4 addon.

Here is the crash log
[crash-2024-02-27_18.10.55-client.txt](https://github.com/GirafiStudios/MineMenu/files/14419348/crash-2024-02-27_18.10.55-client.txt)

**Comment by Momeyuka** [comment]
Below are the documents related to the mod
[menu.json](https://github.com/GirafiStudios/MineMenu/files/14419428/menu.json)

**Comment by BBv22** [comment]
I have the same issue. After some testing, it appears that it happens if you have any keybind actions added to the menu when launching the game.
[log.txt](https://github.com/GirafiStudios/MineMenu/files/14618373/log.txt)
[Faulty menu.json](https://github.com/GirafiStudios/MineMenu/files/14618333/menu.json)
[Working menu.json](https://github.com/GirafiStudios/MineMenu/files/14618428/menu.json)

**Comment by dev-kinsukghosh** [comment]
same here

**Comment by RealZone22** [comment]
Anyone found a fix for this?

**Comment by dev-kinsukghosh** [comment]
i am using 1.20.2 version it works perfectly fine in 1.20.4

**Comment by dev-kinsukghosh** [comment]
@RealZone22   and others

**Comment by RealZone22** [comment]
> i am using 1.20.2 version it works perfectly fine in 1.20.4

After adding a keybind and restarting the game, versions 1.20.4 and 1.20.2 aren't working on fabric.

**Comment by dev-kinsukghosh** [comment]
it something in code that making it crash
